/**
 * @file manifest.ts
 * @description 应用路由唯一真源：以菜单字段为基线，同时承载路由、模式、鉴权与 feature flag 信息。
 */

import type { ModuleId, NavMenuNode } from '../types/moduleMenu';
export type { ModuleId } from '../types/moduleMenu';
export type RouteAuthPolicy = 'public' | 'protected';
export type RouteMenuType = 'page' | 'group' | 'redirect' | 'fallback';

/**
 * 真源节点：
 * - 菜单相关字段以 router/manifest 为唯一真源，运行时由 MenuStore 派生 currentMenuData，便于平滑替换 Sidebar 数据源
 * - 路由/权限相关字段作为扩展字段叠加，不破坏菜单语义
 */
export type AppRouteNode = Omit<NavMenuNode, 'description' | 'exact' | 'children'> & {
  menuDescription: string;
  menuType: RouteMenuType;
  auth?: RouteAuthPolicy;
  menuVisible?: boolean;
  redirect?: string;
  /** 页面模块路径（字符串，如 'pages/StockDashboardPage'）：运行时经 asyncRouteFactory 的 resolvePageImporter 解析为懒加载导入函数 */
  menuPagePath?: string;
  children?: AppRouteNode[];
};

/**
 * 模块节点（真源第一层）：与菜单节点分离建模，便于日后模块走独立的数据库表与字段。
 * - moduleId：模块唯一标识，也是 MenuStore 的 currentModuleId 取值与持久化键。
 * - moduleName / moduleDescription：模块级文案（区别于菜单的 menuName / menuDescription）。
 * - children：模块下的菜单树，节点均为 AppRouteNode。
 */
export type ModuleNode = {
  /** 模块唯一标识（也是 currentModuleId 取值与持久化键） */
  moduleId: ModuleId;
  /** 模块名称：i18n key 或直写文案 */
  moduleName: string;
  /** 模块描述文案 */
  moduleDescription?: string;
  /** 模块根路由路径（可选，用于模块级跳转/重定向） */
  routePath?: string;
  /** 模块所属分组 id（可选，便于日后按分组聚合 / 关联独立模块表） */
  moduleGroupId?: string;
  /** 模块分组名称（可选） */
  moduleGroupName?: string;
  /** 模块图标名（lucide-react 组件名 PascalCase，按名称解析，可选） */
  moduleIcon?: string;
  /** 模块下的菜单树（第一层为菜单/分组，不再含模块自身字段） */
  children: AppRouteNode[];
};

/** 主业务真源：按模块划分的菜单树与页面清单（第一层为 ModuleNode，其 children 为 AppRouteNode）。 */
export const MENU_MANIFEST: ModuleNode[] = [
  {
    moduleId: 'productModel',
    moduleName: '产品',
    moduleDescription: '产品使用模式菜单',
    routePath: '/home',
    moduleGroupId: 'business',
    moduleGroupName: '业务模块',
    moduleIcon: 'LayoutDashboard',
    children: [
      {
        menuId: 'home',
        menuName: 'layout.nav.home.title',
        routePath: '/home',
        menuIcon: 'Home',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.home.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/HomePage',
      },
      {
        menuId: 'stock-dashboard',
        menuName: 'layout.nav.dashboard.title',
        routePath: '/stock-dashboard',
        menuIcon: 'LayoutDashboard',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.dashboard.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/StockDashboardPage',
      },
      {
        menuId: 'sector-analysis',
        menuName: 'layout.nav.sectorAnalysis.title',
        routePath: '/sector-analysis',
        menuIcon: 'LayoutGrid',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.sectorAnalysis.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/SectorAnalysisPage',
      },
      {
        menuId: 'watchlist',
        menuName: 'layout.nav.watchlist.title',
        routePath: '/watchlist',
        menuIcon: 'Star',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.watchlist.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/WatchlistPage',
      },
      {
        menuId: 'live-calendar',
        menuName: 'layout.nav.liveCalendar.title',
        routePath: '/live-calendar',
        menuIcon: 'CalendarDays',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.liveCalendar.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/LiveCalendarPage',
      },
      {
        menuId: 'live-news',
        menuName: 'layout.nav.liveNews.title',
        routePath: '/live-news',
        menuIcon: 'Newspaper',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.liveNews.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/LiveNewsPage',
      },
      {
        menuId: 'kline',
        menuName: 'layout.nav.kline.title',
        routePath: '/kline',
        menuIcon: 'CandlestickChart',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.kline.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/StockKLinePage',
      },
      {
        menuId: 'chat',
        menuName: 'layout.nav.chat.title',
        routePath: '/chat',
        menuIcon: 'MessageSquareQuote',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.chat.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/ChatPage',
      },
      {
        menuId: 'review',
        menuName: 'layout.nav.review.title',
        routePath: '/review',
        menuIcon: 'History',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.review.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/reviewPage',
      },
      {
        menuId: 'portfolio',
        menuName: 'layout.nav.portfolio.title',
        routePath: '/portfolio',
        menuIcon: 'BriefcaseBusiness',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.portfolio.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/PortfolioPage',
      },
      {
        menuId: 'decision-signals',
        menuName: 'layout.nav.decisionSignals.title',
        routePath: '/decision-signals',
        menuIcon: 'Activity',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.decisionSignals.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/DecisionSignalsPage',
      },
      {
        menuId: 'backtest',
        menuName: 'layout.nav.backtest.title',
        routePath: '/backtest',
        menuIcon: 'BarChart3',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.backtest.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/BacktestPage',
      },
      {
        menuId: 'alerts',
        menuName: 'layout.nav.alerts.title',
        routePath: '/alerts',
        menuIcon: 'Bell',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.alerts.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/AlertsPage',
      },
      {
        menuId: 'usage',
        menuName: 'layout.nav.usage.title',
        routePath: '/usage',
        menuIcon: 'Gauge',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.usage.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/TokenUsagePage',
      },
      {
        menuId: 'screening',
        menuName: 'layout.nav.screening.title',
        routePath: '/screening',
        menuIcon: 'Search',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.screening.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/StockScreeningPage',
      },
      {
        menuId: 'code-test',
        menuName: 'layout.nav.codeTest.title',
        routePath: '/codeTest',
        menuIcon: 'FlaskConical',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.codeTest.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/CodeTestPage',
      },
      {
        menuId: 'settings',
        menuName: 'layout.nav.settings.title',
        routePath: '/settings',
        menuIcon: 'Settings2',
        menuPosition: 'footer',
        level: 0,
        menuExpanded: false,
        menuDescription: 'layout.nav.settings.description',
        menuType: 'page',
        auth: 'protected',
        menuVisible: true,
        menuPagePath: 'pages/SettingsPage',
      },
    ],
  },
  {
    moduleId: 'developmentMode',
    moduleName: '开发调试',
    moduleDescription: '开发调试模式菜单',
    routePath: '/docs-input',
    moduleGroupId: 'debug',
    moduleGroupName: '调试模块',
    moduleIcon: 'FlaskConical',
    children: [
      {
        menuId: 'Basic',
        menuName: '基础',
        routePath: '',
        menuIcon: 'Component',
        menuBadge: '',
        menuPosition: 'content',
        level: 0,
        menuExpanded: true,
        menuDescription: '基础',
        menuType: 'group',
        menuVisible: true,
        children: [
          {
            menuId: 'docs-button',
            menuName: 'layout.nav.development.docsButton.title',
            routePath: '/docs/component/button',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsButton.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_button',
          },
        ],
      },
      {
        menuId: 'Form',
        menuName: '表单',
        routePath: '',
        menuIcon: 'FormInput',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: '表单',
        menuType: 'group',
        menuVisible: true,
        children: [
          {
            menuId: 'docs-input',
            menuName: 'layout.nav.development.docsInput.title',
            routePath: '/docs/component/input',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsInput.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_input',
          },
          {
            menuId: 'docs-text-area',
            menuName: 'layout.nav.development.docsTextArea.title',
            routePath: '/docs/component/textArea',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsTextArea.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_textArea',
          },
          {
            menuId: 'docs-select',
            menuName: 'layout.nav.development.docsSelect.title',
            routePath: '/docs/component/select',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsSelect.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_select',
          },
          {
            menuId: 'docs-checkbox',
            menuName: 'layout.nav.development.docsCheckbox.title',
            routePath: '/docs/component/checkbox',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsCheckbox.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_checkbox',
          },
        ],
      },
      {
        menuId: 'DataDisplay',
        menuName: '数据展示',
        routePath: '',
        menuIcon: 'Database',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: '数据展示',
        menuType: 'group',
        menuVisible: true,
        children: [
          {
            menuId: 'docs-chip',
            menuName: 'layout.nav.development.docsChip.title',
            routePath: '/docs/component/chip',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsChip.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_chip',
          },
          {
            menuId: 'docs-table',
            menuName: 'layout.nav.development.docsTable.title',
            routePath: '/docs/component/table',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsTable.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_table',
          },
        ],
      },
      {
        menuId: 'Navigation',
        menuName: '导航',
        routePath: '',
        menuIcon: 'Navigation',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: '导航',
        menuType: 'group',
        menuVisible: true,
        children: [
          {
            menuId: 'docs-side-bar',
            menuName: 'layout.nav.development.docsSideBar.title',
            routePath: '/docs/component/sideBar',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsSideBar.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_sideBar',
          },
          {
            menuId: 'docs-tab-nav',
            menuName: 'layout.nav.development.docsTabNav.title',
            routePath: '/docs/component/tabNav',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsTabNav.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_tabNav',
          },
        ],
      },
      {
        menuId: 'Layout',
        menuName: '布局',
        routePath: '',
        menuIcon: 'LayoutTemplate',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: '布局',
        menuType: 'group',
        menuVisible: true,
        children: [
          {
            menuId: 'docs-separator',
            menuName: 'layout.nav.development.docsSeparator.title',
            routePath: '/docs/component/separator',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsSeparator.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_separator',
          },
          {
            menuId: 'docs-anim-card',
            menuName: 'layout.nav.development.docsAnimCard.title',
            routePath: '/docs/component/animCard',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsAnimCard.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_animCard',
          },
          {
            menuId: 'docs-news-card',
            menuName: 'layout.nav.development.docsNewsCard.title',
            routePath: '/docs/component/newsCard',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsNewsCard.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_newsCard',
          },
          {
            menuId: 'docs-list-card',
            menuName: 'layout.nav.development.docsListCard.title',
            routePath: '/docs/component/listCard',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsListCard.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_listCard',
          },
        ],
      },
      {
        menuId: 'Overlays',
        menuName: '浮层',
        routePath: '',
        menuIcon: 'Layers',
        menuPosition: 'content',
        level: 0,
        menuExpanded: false,
        menuDescription: '浮层',
        menuType: 'group',
        menuVisible: true,
        children: [
          {
            menuId: 'docs-drawer',
            menuName: 'layout.nav.development.docsDrawer.title',
            routePath: '/docs/component/drawer',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsDrawer.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_drawer',
          },
          {
            menuId: 'docs-toast',
            menuName: 'layout.nav.development.docsToast.title',
            routePath: '/docs/component/toast',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsToast.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_toast',
          },
          {
            menuId: 'docs-modal',
            menuName: 'layout.nav.development.docsModal.title',
            routePath: '/docs/component/modal',
            menuPosition: 'content',
            level: 1,
            menuExpanded: false,
            menuDescription: 'layout.nav.development.docsModal.description',
            menuType: 'page',
            auth: 'protected',
            menuVisible: true,
            menuPagePath: 'pages/DocsPage/Components/Docs_modal',
          },
        ],
      },
    ],
  },
];


export const isPageLikeRouteNode = (
  node: AppRouteNode,
): node is AppRouteNode & { menuType: 'page' | 'redirect' | 'fallback' } =>
  node.menuType === 'page' || node.menuType === 'redirect' || node.menuType === 'fallback';
