import type { ComponentType } from 'react';
import {
  Activity,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  CalendarDays,
  CandlestickChart,
  Component,
  Database,
  FlaskConical,
  FormInput,
  Gauge,
  History,
  Home,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  MessageSquareQuote,
  Navigation,
  Newspaper,
  Search,
  Settings2,
  Star,
} from 'lucide-react';

/**
 * 菜单图标白名单：图标名 → lucide 组件。菜单数据仅存图标名字符串（可序列化、可持久化），
 * 渲染层据此解析回组件。集中在此文件以保持 tree-shaking（仅这 23 个图标进入产物）。
 */
export const menuIconRegistry: Record<string, ComponentType<{ className?: string }>> = {
  Activity,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  CalendarDays,
  CandlestickChart,
  Component,
  Database,
  FlaskConical,
  FormInput,
  Gauge,
  History,
  Home,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  MessageSquareQuote,
  Navigation,
  Newspaper,
  Search,
  Settings2,
  Star,
};
